# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

categories = ["Advocacy", "Banking & Finance", "Building & Construction", "Commercial", "Corporate", "Costs", "Dispute Resolution/Mediation", "Employment & Industrial Relations", "Ethics", "Family", "Public & Admin Law", "Health & Aged Care", "Leases", "In-house Counsel", "Insolvency", "Intellectual Property", "Litigation", "Medico-legal", "Migration",  "Personal Injury", "Planning & Environment", "Privacy & FOI", "Property", "Sports Law", "Superannuation", "Tax", "Trusts","Wills & Estates"]

if Category.all.length == 0
    categories.each do |category|
        Category.create(name: category)
        puts "created #{category} category"
    end
end

Course.create(title: "Alert! Social Media, Voller and Defamation Law Update", description: "The recent High Court decision in the matter between various media organisations and Dylan Voller has brought to light and confirmed the definition of ‘publisher’ of social media posts.Our presenters will discuss the High Court’s decision and the implications for media organisations, businesses and even individuals and their use of social media platforms to share and generate content.The session will also cover the defences available and how this decision interacts with recent Defamation Law reforms.", fee: 155, start_time: "2021-12-07 13:00:00.000000000 +0000", instructor_name: "Richard Leder OAM", substantive_law: 1, url: "https://store.leocussen.edu.au/product/alert-social-media-voller-and-defamation-law-update", end_time: "2021-12-07 14:00:00.000000000 +0000", instructor_role: "Partner, Corrs Chambers Westgarth", category_id: 3)
Course.create(title: "Online Legal Research - Tips for Working Remotely", description: "This session is designed to unlock the secrets to free legal research sites and tools. With restricted or limited resources available as the majority of us work remotely, this is a critical and practical session for all legal practitioners.This session will provide a step by step guide to research legislation, case law and other legal material online using the latest free tools.Discover a wide range of available online resources you never knew existed. Bring back this knowledge to your firm and divulge ‘the secrets’!This session is a great investment that will save you time and increase your productivity!Presented by: Michael Gavan, Legal Knowledge Researcher, MinterEllison What is included:A video of the presentation in mp4 formatPaper material in pdf format* This Webcast does not allow WA practitioners to claim CPD points", fee: 130, start_time: "2021-11-16 18:16:00.000000000 +0000", instructor_name: "Michael Gavan", professional_skills: 1, url: "https://store.leocussen.edu.au/product/online-legal-research-tips-for-working-remotely-o20060?taxon_id=6", end_time: "2000-01-01 18:17:00.000000000 +0000", instructor_role: "Know-How Team Leader & Research Librarian, MinterEllison", category_id: 3 )
Course.create(title: "Wills & Estates Planning - Dealing with COVID-19 Impact & Issues", description: "This one hour CPD seminar is designed to help you identify and guide you through the essential issues to focus on and how to manage your clients and risks.During this session a leading practitioner will focus on the major issues including: Estate Planning At home will-kits - pros and cons Documents, witness & signing in self-isolation or loss of capacity Enduring Power of Attorney and Appointment of Medical Treatment Decision Maker / Enduring Guardian Formulating a contingency plan in a time of crisis Presented by: Ines Kallweit, Principal & Accredited Specialist (LIV) – Wills & Estates, KHQ Lawyers What is included:A video of the presentation in mp4 formatPaper material in pdf format* This Webcast does not allow WA practitioners to claim CPD points", fee: 130, start_time: "2021-12-10 09:00:00.000000000 +0000", instructor_name: "Ines Kallweit", substantive_law: 1, url: "https://store.leocussen.edu.au/product/wills-estates-planning-dealing-with-covid-19-impact-issues-o20039", end_time: "2021-12-10 12:30:00.000000000 +0000", instructor_role: "Principal Solicitor, Wills & Estates Accredited Specialist, KHQ Lawyers", category_id: 29)
Course.create(title: "3 CPD Point Intensive", description: "Working remotely from home, though it has its benefits, has been an adjustment for us all. This session will emphasise how to take time and task management to another level which includes current expectations involving work, family and other personal commitments. This session is designed to assist in identifying deep work, which is the ability to work with distraction free concentration, and how this can improve productivity and a sense of purpose when working from home by focusing on:Identifying what is deep work vs shallow workHow to achieve deep work with the distractions of home-schooling and working from homeHow deep work improves wellbeing3 ways to schedule deep work into your lifeTips and rituals to help you do deep workHow downtime increases deep work (through micro breaks and a shutdown ritual)How to reduce shallow “busy” work", fee: 425, start_time: "2022-03-08 09:00:00.000000000 +0000", instructor_name: "Lauren Kelindeman", ethics: 1, url: "https://store.leocussen.edu.au/product/3-cpd-point-intensive-i21036", end_time: "2022-03-08 15:30:00.000000000 +0000", instructor_role: "Commercial and Franchising Lawyer, Legalite", category_id: 3)
Course.create(title: "Employment and Industrial Relations Law - Practice and Procedure (Mar 2022)", description: "This practical workshop focuses on the powers and workings of the Fair Work Commission (FWC), unfair dismissal and unlawful termination applications to FWC, common law claims for wrongful dismissal, drafting employment contracts considering both statute and common law and an overview of discrimination and equal opportunity laws. Key cases, legislation and practice notes relating to this practice area are also discussed. Covid-19 has also resulted in legal and practical updates in this rapidly evolving and often complex area.   Essential workshops are for lawyers new to or wanting to update knowledge in a particular practice area. Workshops are interactive, practical and aim to cover the essential skills, knowledge and expertise required for that particular area.", fee: 675, start_time: "2021-12-01 10:00:00.000000000 +0000", instructor_name: "Jim McKenna", professional_skills: 2, url: "https://store.leocussen.edu.au/product/employment-and-industrial-relations-law-practice-and-procedure-mar-2022", end_time: "2021-12-03 13:00:00.000000000 +0000", instructor_role: "Barrister, Victorian Bar", category_id: 1)
Course.create(title: "Mental Health First Aid for Legal Professionals Accredited Workshop (Dec)", description: "This Workshop is complemented by an eLearning component completed prior to the workshop (Workshop Day One: Wednesday 10am–1pm, Workshop Day Two: Friday 10am–1pm).In Australia, nearly 1 in 5 of adults will experience a mental illness in any one year. Within the legal profession the incidence is far greater with 1 in 3 lawyers at any one stage suffering heightened stress and anxiety, depression, and substance use disorders.This Course will train you to assist a colleague who is developing a mental health problem or suffering a mental health crisis. Become an Accredited Mental Health First Aider and learn skills that give you the confidence to deal with these issues as they arise.Together with legalsuper, Leo Cussen is proud to deliver this important course to the legal profession.*Please note this workshop is run across two half days Presented By: Desi Vlahos, Accredited Mental First Aid Instructor, Mentor and Lawyer, Leo Cussen Centre for Law", fee: 520, start_time: "2021-12-01 10:00:00.000000000 +0000", instructor_name: "Desi Vlahos", professional_skills: 2, url: "https://store.leocussen.edu.au/product/mental-health-first-aid-for-legal-professionals-accredited-workshop-dec", end_time: "2021-12-03 13:00:00.000000000 +0000", instructor_role: "Accredited Mental First Aid Instructor, Mentor and Lawyer, Leo Cussen Centre for Law", category_id: 12 )
Course.create(title: "Planning Law Practice - From permit to enforcement (Dec 2021)", description: "This workshop is designed to give practitioners an introduction and overview of the planning system in Victoria. It will introduce practitioners to the application, objection and appeals procedure and includes a selection of Case Studies to be considered and discussed in relation to the procedures and issues involved. The enforcement provisions of the Planning and Environment Act 1987 and other controls will also be considered.Topics include:    Planning framework including legislation    Planning and responsible authorities    Planning schemes    Zoning    Amendments    Applications for review    Compensation    Proceedings in VCAT    Application processes    Objections    Submissions", fee: 670, start_time: "2021-12-01 09:00:00.000000000 +0000", instructor_name: "Natalie Blok", professional_skills: 1, url: "https://store.leocussen.edu.au/product/planning-law-practice-from-permit-to-enforcement-nov-21", end_time: "2021-12-01 15:30:00.000000000 +0000", instructor_role: "Barrister, Victorian Bar", category_id: 22) 
 
    
Course.create(title: "Directors Duties, Legal Advice and COVID-19", description: "The duties and responsibilities imposed on company directors and officers have never been more serious, in light of the COVID-19 crisis. The requirement for legal advisers to be across ongoing changes and current developments have never been more important.The potential consequences from making the wrong decisions can be wide reaching and legal advisers need to be ready to give advice relating to a myriad of complex situations.This seminar will examine recent developments, including to what extent directors should be aware of potential breaches of the law, whether there is a new standard to which directors will be held responsible for decision making and the risks and opportunities that the COVID-19 pandemic has presented to boards, directors and officers.This is a seminar not to be missed! Presented by: Kim Mackay, Partner, Holding Redlich What is included:A video of the presentation in mp4 formatPaper material in pdf format* This Webcast does not allow WA practitioners to claim CPD points", fee: 130, instructor_name: "Kim Mackay", substantive_law: 1, url: "https://store.leocussen.edu.au/product/directors-duties-legal-advice-and-covid-19-o20072?taxon_id=2", instructor_role: "Partner, Holding Redlich", category_id: 5) 
Course.create(title: "Retail and Commercial Leases - A practical guide (Nov 2021)", description: "This workshop covers the essentials of retail leasing and is ideal for both private practice and in-house lawyers.The program includes: An overview of the retail leases legislation Disclosure statements Key conditions Procedural steps Stamp duty Transfers Surrenders Recovering possession Stay ahead of the pack! This workshop is designed to bring you up to date with current practice, procedures and skills in this area. It is ideal for practitioners new to retail leasing practice as well a refresher for those already practising in this area. Presented by: Mark Flynn, Partner, McKean Park LawyersEssential workshops are for lawyers new to or wanting to update knowledge in a particular practice area. Workshops are interactive, practical and aim to cover the essential skills, knowledge and give confidence to practise in that area.", fee: 670, start_time: "2021-11-22 09:00:00.000000000 +0000", instructor_name: "Mark Flynn", substantive_law: 5, url: "https://store.leocussen.edu.au/product/retail-and-commercial-leases-a-practical-guide-nov-2021", end_time: "2021-11-22 15:30:00.000000000 +0000", instructor_role: "McKean Park Lawyers", category_id: 24) 
 
Course.create(title: "Elderly Clients Half Day Conference | Advice, Risk Management & Remedies", description: "This program has been designed to help equip Legal Practitioners with the knowledge and skills to understand and manage the unique circumstances surrounding legal matters involving elderly clients/parties and how best to advise them and mitigate risks.By the end of this program a Legal Practitioner should know what to look out for with regard to capacity and elder abuse and how best to advise on complex contracts, such as Retirement Village Agreements. You should also know what your professional obligations are to your elderly clients and or elderly parties to a legal transaction.", fee: 525, start_time: "2021-11-27 09:00:00.000000000 +0000", instructor_name: "Dan Coombes", practice_management: 1, url: "https://store.leocussen.edu.au/product/elderly-clients-half-day-conference-elder-abuse-capacity-risk-management-remedies", end_time: "2021-11-27 13:30:00.000000000 +0000", instructor_role: "Barrister, Victorian Bar", category_id: 29 ) 

Course.create(title: "CPD 5 Point Online Bundle (to Download)", description: "What is included:Videos of the presentation in mp4 format.Paper materials in pdf format.* This Webcast does not allow WA practitioners to claim CPD points", fee: 395, instructor_name: "Suzanne McNicol QC", professional_skills: 2, url: "https://store.leocussen.edu.au/product/cpd-5-point-online-bundle-to-download?taxon_id=3", instructor_role: "Barrister, Victorian Bar", category_id: 3) 

Course.create(title: "Subject to Finance Clauses - Cover you and your client!", description: "Subject to finance clauses have always required caution and even more so during COVID-19. With tighter lending practices and obtaining finance in the current economic climate, advising your client about how subject to finance clauses work is crucial.This session will cover: Buyer and sellers rights under a subject to finance clause; Finance clause extensions of time – Tips and traps; Dangers of informal arrangements and undocumented extensions; Failure to keep solicitor/ broker updated with developments; Breaching the subject to finance clause – What happens then? Ending contracts due to failure to obtain finance; Solicitors advising clients and what they need to remember/ Solicitors checklist; Cases of significance discussed. Presented by: Kristy Muhlhan, Principal, Burke & Associates Lawyers What is included:A video of the presentation in mp4 formatPaper material in pdf format* This Webcast does not allow WA practitioners to claim CPD points", fee: 130, instructor_name: "Kristy Muhlhan", substantive_law: 1, url: "https://store.leocussen.edu.au/product/subject-to-finance-clauses-cover-you-and-your-client-o21012", instructor_role: "Principal, Burke & Associates Lawyers", category_id: 4) 

Course.create(title: "Superannuation Law - COVID-19 - Legal and Regulatory Issues for Superannuation Funds", description: "This one hour CPD seminar is designed to help you identify and guide you through the essential issues to focus on and how to manage your clients and risks.During this session a leading practitioner will focus on the major issues including:Government and Regulator responses such as the early release of superannuation savings and minimum drawdown rates for retirees, changes in FIRB requirements, changes in insolvency rules and APRA liquidity surveillance and modifications to APRA and ASIC reporting.It will also address topics including force majeure and other tax measures which have an indirect impact on the investments which super funds make, as well as key governance issues that have arisen as a result of COVID-19.This seminar is a must for all superannuation lawyers! Presented by: Jim Bulling, Partner, K&L Gates What is included:A video of the presentation in mp4 formatPaper material in pdf format* This Webcast does not allow WA practitioners to claim CPD points", fee: 130, instructor_name: "Jim Bulling", substantive_law: 1, url: "https://store.leocussen.edu.au/product/superannuation-law-covid-19-legal-and-regulatory-issues-for-superannuation-funds-o20043", instructor_role: "Partner, K&L Gates", category_id: 26) 

Course.create(title: "Time Management and File Productivity During COVID-19", description: "With so many of us forced to work from home, time management is the key to thriving in and out of the workplace. As our professional and personal spaces merge, self burnout is a real, increasing threat. Hear from experienced practitioners about how to increase productivity at work to make more time for the things you love. During this session a leading practitioner will focus on the major issues including: Identifying what tasks should be done at what time in the day Using technology to organise your systems more efficiently Prioritising work using two easy and effective methods How to limit undesirable or unnecessary work The importance of wellbeing and rest to your productivity Presented by: Marianne Marchesi, Principal Lawyer, LegaliteandLauren Kelindeman, Commercial and Franchising Lawyer, Legalite What is included:A video of the presentation in mp4 formatPaper material in pdf format* This Webcast does not allow WA practitioners to claim CPD points", fee: 130, instructor_name: "Marianne Marchesi", practice_management: 1, url: "https://store.leocussen.edu.au/product/time-management-and-file-productivity-during-covid-19-o20059", instructor_role: "Principal Lawyer, Legalite", category_id: 3) 

Course.create(title: "Appearing in Court - Maximise your Performance and Avoid Complaints", description: "Appearing in Court- Maximise your Performance and Gain Confidence   This session will give you the confidence you need when appearing in courts as well as tips for obtaining the best outcome for your client on the day. This session has been adapted to apply to in-person and remote appearances.This seminar will address the following with reference to in-person and remote appearances as required : Interacting with opposing representatives Standing matters down Preparing yourself and your client  Familiarise yourself with the court procedures Dealing with the registry Advocacy tips and tricks Appearing with confidence and overcoming the nerves Announcing your appearance Obtaining your client’s instructions from the Bar table Handing up documents Leaving the Bar table Addressing the judicial officer presiding Fight for your client: How far can you go Whilst confidence is one skill necessary when representing your client, how far can you go when advocating for them? What is considered robust representation and what is considered crossing the line? By reference to Victorian Legal Services Commissioner v McDonald 57 VR 186 [2019] VSCA 18, this session will discuss exactly how far you can go when representing your client so as not to breach your professional conduct obligations: Appropriate use of communication and language Email and Written Correspondence How to respond when challenged", fee: 215, start_time: "2021-11-09 12:00:00.000000000 +0000", instructor_name: "Kate Anderson", ethics: 1, url: "https://store.leocussen.edu.au/product/appearing-in-court-maximise-your-performance-and-avoid-complaints", end_time: "2021-11-09 13:30:00.000000000 +0000", instructor_role: "Barrister, Victorian Bar", category_id: 1 )

Course.create(title: "Legal Professional Privilege - Risk of Loss Through Technology", description: "Cases including Glencore International AG & Ors v Commissioner of Taxation of the Commonwealth of Australia & Ors show that the ability to rely on LPP can depend on the steps taken and timing of those steps. It also highlights the adverse outcomes in a claim that can arise once information is in th public domain. What rights and remedies does a party have once the material is in the public domain?The risk of loss of LPP may increase through greater reliance on technology. Particularly in the event of security breaches, staff access to and inadvertent sharing of information when working remotely and client sharing of information on social media.What are the obvious risks through use of technology and how can those risks be minimised.This session will outline the current legal position around LPP and highlight the particular risks regarding technology with reference to the case of TEC Hedland Pty Ltd v The Pilbara Infrastructure Pty Ltd [2020]. It will also address the steps that should be taken to minimise those risks. Presented by: Graydon Dowd, Partner, Hall & Wilcox What is included:A video of the presentation in mp4 format* This Webcast does not allow WA practitioners to claim CPD points", fee: 130, instructor_name: "Graydon Dowd", substantive_law: 1, url: "https://store.leocussen.edu.au/product/legal-professional-privilege-risk-of-loss-through-technology-o21053?taxon_id=2", instructor_role: "Partner, Hall & Wilcox", category_id: 3)

 
Course.create(title: "Time Management - Finding 25 Hours in a Day", description: "How do you stay in control whilst trying to meet or exceed client and colleague demands and expectations? Access and availability is often expected at all hours of the day and night and it is easy to become overwhelmed.Time management is the key to surviving and thriving as a lawyer. Hear from an experienced practitioner about what they do to increase productivity and deliver at the highest level.This seminar is designed to reveal the strategies that successful lawyers use to maximise every minute of the day and achieve client and personal satisfaction.", fee: 124, start_time: "2022-02-03 13:00:00.000000000 +0000", instructor_name: "Lauren Kelindeman", practice_management: 1, url: "https://store.leocussen.edu.au/product/time-management-finding-25-hours-in-a-day-s21312", end_time: "2022-02-03 14:00:00.000000000 +0000", instructor_role: "Commercial and Franchising Lawyer, Legalite", category_id: 3)

Course.create(title: "Retail and Commercial Leases - A practical guide (Feb 2022)", description: "This workshop covers the essentials of retail leasing and is ideal for both private practice and in-house lawyers. The program includes: An overview of the retail leases legislation Disclosure statements Key conditions Procedural steps Stamp duty Transfers Surrenders Recovering possession Stay ahead of the pack! This workshop is designed to bring you up to date with current practice, procedures and skills in this area. It is ideal for practitioners new to retail leasing practice as well a refresher for those already practising in this area.   Essential workshops are for lawyers new to or wanting to update knowledge in a particular practice area. Workshops are interactive, practical and aim to cover the essential skills, knowledge and give confidence to practise in that area.", fee: 675, start_time: "2022-02-03 09:00:00.000000000 +0000", instructor_name: "null", substantive_law: 5, url: "https://store.leocussen.edu.au/product/retail-and-commercial-leases-a-practical-guide-feb-2022", end_time: "2022-02-03 15:30:00.000000000 +0000", instructor_role: "null", category_id: 24)

Course.create(title: "Property Law - Dealing with COVID-19 Impact on Residential Leases", description: "This one hour CPD seminar is designed to help you identify and guide you through the essential issues to focus on and how to manage your clients and risks.During this session a leading practitioner will focus on the major issues including: Eviction Notices Inspections and Open Homes Loss of Income Insurance Government Protection Measures Landlord’s and Tenant’s rights and responsibilities Presented by: William Stark, Barrister, Victorian Bar What is included:A video of the presentation in mp4 formatPaper material in pdf format* This Webcast does not allow WA practitioners to claim CPD points", fee: 130, instructor_name: "William Stark", substantive_law: 1, url: "https://store.leocussen.edu.au/product/property-law-dealing-with-covid-19-impact-on-residential-leases-o20045", instructor_role: "Barrister, Victorian Bar", category_id: 24)

Course.create(title: "Property Law - Dealing with COVID-19 Impact on Residential Leases", description: "This one hour CPD seminar is designed to help you identify and guide you through the essential issues to focus on and how to manage your clients and risks.During this session a leading practitioner will focus on the major issues including: Eviction Notices Inspections and Open Homes Loss of Income Insurance Government Protection Measures Landlord’s and Tenant’s rights and responsibilities Presented by: William Stark, Barrister, Victorian Bar What is included:A video of the presentation in mp4 formatPaper material in pdf format* This Webcast does not allow WA practitioners to claim CPD points", fee: 130, instructor_name: "William Stark", substantive_law: 1, url: "https://store.leocussen.edu.au/product/property-law-dealing-with-covid-19-impact-on-residential-leases-o20045", instructor_role: "Barrister, Victorian Bar", category_id: 24)

Course.create(title: "Property Law Intensive", description: "Off-the-plan contracts continue to constitute one of the main areas of dispute in property law. Many of these disputes arise from disagreement over whether amendments made to the plan of subdivision after the contract has been signed constitute ’material’ or ’non-material’ changes. When the rights of both parties can be so significantly affected by this distinction, it is vitally important to be aware of just what amendments are permissible.This session will provide an update on recent cases, addressing the ‘material’ versus ‘non-material’ issue as well as other areas of dispute in off-the-plan sales, and the key learnings to be taken from them.This session will include:Amendments to the plan of subdivision;Changes to the development;Material vs Non-Material changes;Sunset clauses;Changes to size/area of the lot;Finishes, quality and defects;Owners corporations and common property;Misrepresentation and consumer law;Failure to disclose.", fee: 425, start_time: "2021-11-25 09:00:00.000000000 +0000", instructor_name: "Louise Hicks", practice_management: 1, url: "https://store.leocussen.edu.au/product/property-law-intensive-i21037", end_time: "2021-11-25 12:30:00.000000000 +0000", instructor_role: "Barrister, Victorian Bar", category_id: 24)

