# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Category.create(category: 'Advocacy')
Category.create(category: 'Banking & Finance')
Category.create(category: 'Building & Construction')
Category.create(category: 'Commercial')
Category.create(category: 'Corporate')
Category.create(category: 'Costs')
Category.create(category: 'Criminal')
Category.create(category: 'Dispute Resolution/Mediation')
Category.create(category: 'Employment & Industrial Relations')
Category.create(category: 'Ethics')
Category.create(category: 'Family')
Category.create(category: 'Public & Admin Law')
Category.create(category: 'Health & Aged Care')
Category.create(category: 'Leases')
Category.create(category: 'In-house Counsel')
Category.create(category: 'Insolvency')
Category.create(category: 'Intellectual Property')
Category.create(category: 'Litigation')
Category.create(category: 'Medico-legal')
Category.create(category: 'Migration')
Category.create(category: 'Personal Injury')
Category.create(category: 'Planning and Environment')
Category.create(category: 'Privacy & FOI')
Category.create(category: 'Property')
Category.create(category: 'Sports Law')
Category.create(category: 'Superannuation')
Category.create(category: 'Tax')
Category.create(category: 'Trusts')
Category.create(category: 'Wills & Estates')
